version: '3.8'

services:
  webapi:
    image: library
    build:
      context: ./Library.WebAPI
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - 8081:8081
    depends_on:
      - db
    extra_hosts:
    - "host.docker.internal:host-gateway"
  

  db:
    container_name: Library.WebAPI
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: LibraryDb
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: